all_expected_cols = [
 'Financial Aid Offered Amount',
 'incoming_text_count',
 'outgoing_text_count',
 'phone_successful_count',
 'phone_unsuccessful_count',
 'phone_voicemail_count',
 'Admitted Students Day',
 'Bison Day',
 'Bison Day @ The Weekend',
 'Campus Visit',
 'Dallas Bison Exclusive',
 'Football Visit',
 'Golf Visit',
 'Oklahoma City Bison Exclusive',
 'Scholars Bison Day',
 'Scholarship Interview',
 'Scholarship Interview Registration',
 'Softball Visit',
 'Track Visit',
 'Tulsa Bison Exclusive',
 'Volleyball Visit',
 'Events Attended Count',
 'Scholars Mixer And Banquet',
 'Country_ARE',
 'Country_ARG',
 'Country_BDI',
 'Country_BEN',
 'Country_BFA',
 'Country_BGD',
 'Country_BHS',
 'Country_BRA',
 'Country_BRB',
 'Country_BWA',
 'Country_CAN',
 'Country_CHE',
 'Country_CHL',
 'Country_CMR',
 'Country_COD',
 'Country_CUB',
 'Country_CYP',
 'Country_CZE',
 'Country_DEU',
 'Country_ESP',
 'Country_ETH',
 'Country_FRA',
 'Country_GBR',
 'Country_GHA',
 'Country_GMB',
 'Country_HKG',
 'Country_HND',
 'Country_IND',
 'Country_IRN',
 'Country_ITA',
 'Country_JAM',
 'Country_KAZ',
 'Country_KEN',
 'Country_KWT',
 'Country_LBR',
 'Country_LKA',
 'Country_LSO',
 'Country_MAR',
 'Country_MDG',
 'Country_MEX',
 'Country_MMR',
 'Country_MNG',
 'Country_MWI',
 'Country_NAM',
 'Country_NGA',
 'Country_NLD',
 'Country_NPL',
 'Country_NZL',
 'Country_Not Declared',
 'Country_OMN',
 'Country_PAK',
 'Country_PER',
 'Country_PHL',
 'Country_PNG',
 'Country_PSE',
 'Country_ROU',
 'Country_RWA',
 'Country_SAU',
 'Country_SEN',
 'Country_SLE',
 'Country_SLV',
 'Country_SSD',
 'Country_SWZ',
 'Country_TGO',
 'Country_TJK',
 'Country_TUR',
 'Country_TZA',
 'Country_UGA',
 'Country_URY',
 'Country_USA',
 'Country_UZB',
 'Country_VEN',
 'Country_VNM',
 'Country_WSM',
 'Country_ZAF',
 'Country_ZMB',
 'Country_ZWE',
 'State_-- Select --',
 'State_AB',
 'State_ADDIS ABABA',
 'State_AE',
 'State_AK',
 'State_AL',
 'State_ANAMBRA',
 'State_AP',
 'State_AR',
 'State_ASHANTI',
 'State_ASHANTI REGION',
 'State_AZ',
 'State_Abia',
 'State_Addis Ababa',
 'State_Akwa Ibom',
 'State_Al Farwaniyah',
 'State_Almaty',
 'State_Anambra',
 'State_Andhra Pradesh',
 'State_Antananarivo',
 'State_Araucania',
 'State_Artigas',
 'State_Ashanti',
 'State_BC',
 'State_BONO EAST',
 'State_Bagmati',
 'State_Balochistan',
 'State_Banjul',
 'State_Baringo',
 'State_Barisal',
 'State_Bihar',
 'State_Bolivar',
 'State_Bong',
 'State_Brong-Ahafo',
 'State_Buenos Aires',
 'State_Bujumbura',
 'State_CA',
 'State_CAPITAL CITY',
 'State_CENTRAL REGION',
 'State_CO',
 'State_CT',
 'State_Central',
 'State_Central Equatoria',
 'State_Central River Division',
 'State_Centre',
 'State_Chittagong Division',
 'State_Colon',
 'State_Cross River',
 'State_DAKAR',
 'State_DC',
 'State_DE',
 'State_Dar es Salaam',
 'State_Delhi',
 'State_Delta',
 'State_Dhaka Division',
 'State_Doukkala-Abda',
 'State_Dubai',
 'State_Dushanbe',
 'State_ENUGU STATE',
 'State_ETHIOPIA',
 'State_East Kazakhstan',
 'State_Eastern',
 'State_Eastern Cape',
 'State_Eastern Visayas',
 'State_Edo',
 'State_Elgeyo-Marakwet',
 'State_Enga',
 'State_Enugu',
 "State_FARG'ONA VILOYATI",
 'State_FERGANA',
 'State_FL',
 'State_Famagusta',
 'State_Fars',
 'State_Federal Capital Territory',
 'State_Fergana',
 'State_Francisco Morazan',
 'State_GA',
 'State_GHANA',
 'State_GREATER ACCRA',
 'State_GUATENG',
 'State_Gandaki',
 'State_Garissa',
 'State_Gauteng',
 'State_Gaza',
 'State_Gilgit-Baltistan',
 'State_Grand Casablanca',
 'State_Greater Accra',
 'State_HI',
 'State_Harare',
 'State_Harghita',
 'State_Herat',
 'State_Hesse',
 'State_Hhohho',
 'State_IA',
 'State_ID',
 'State_IL',
 'State_IN',
 'State_ISLAMABAD CAPITAL TERRITORY',
 'State_Imo',
 'State_Istanbul',
 'State_JANAKPUR',
 'State_KANESHIE',
 'State_KERICHO',
 'State_KS',
 'State_KY',
 'State_Kaduna',
 'State_Kericho',
 'State_Khyber Pakhtunkhwa',
 'State_Kiambu',
 'State_Kigali',
 'State_Kinshasa',
 'State_Kisii',
 'State_KwaZulu-Natal',
 'State_Kwara',
 'State_LA',
 'State_LAGOS',
 'State_Lagos',
 'State_Lambayeque',
 'State_Limpopo',
 'State_Littoral',
 'State_MA',
 'State_MD',
 'State_ME',
 'State_MI',
 'State_MN',
 'State_MO',
 'State_MS',
 'State_MT',
 'State_Madhesh Pradesh',
 'State_Madhya Pashchimanchal',
 'State_Madrid Autonomous Community',
 'State_Maharashtra',
 'State_Manicaland',
 'State_Manipur',
 'State_Manzini',
 'State_Maritime',
 'State_Maseru',
 'State_Metro Manila',
 'State_Mexico City',
 'State_Minas Gerais',
 'State_Mombasa',
 'State_Montserrado',
 'State_Morazan',
 'State_Mpumalanga',
 'State_Muscat',
 'State_NC',
 'State_ND',
 'State_NE',
 'State_NH',
 'State_NJ',
 'State_NM',
 'State_NV',
 'State_NY',
 'State_Nairobi County',
 'State_Namangan',
 'State_Nandi',
 'State_New Providence',
 'State_Nimba',
 'State_North Kivu',
 'State_North Rhine-Westphalia',
 'State_Northern',
 'State_Northern Ireland',
 'State_Northwest',
 'State_Not Declared',
 'State_OH',
 'State_OK',
 'State_ON',
 'State_OR',
 'State_Odisha',
 'State_Ogun',
 'State_Ondo',
 'State_Oromia',
 'State_Oshana',
 'State_Osun',
 'State_Oyo',
 'State_Oyo State',
 'State_PA',
 'State_PR',
 'State_PUNJAB',
 'State_Parana',
 'State_Piedmont',
 'State_Plateau',
 'State_Prague',
 'State_Punjab',
 'State_Purwanchal',
 'State_Qashqadaryo',
 'State_Quang Nam',
 'State_RI',
 'State_RIO GRANDE DO NORTE',
 'State_Rivers',
 'State_SANCTI SPIRITUS',
 'State_SC',
 'State_SD',
 'State_SOUTHWEST REGION',
 'State_Sabaragamuwa',
 'State_Sagaing',
 'State_Saint Catherine',
 'State_Saint James',
 'State_Saint Philip',
 'State_Samarqand',
 'State_Sao Paulo',
 'State_Scotland',
 'State_Sindh',
 'State_Southern',
 'State_Southwest',
 'State_Sudur Pashchimanchal',
 'State_Sylhet Division',
 'State_TN',
 'State_TX',
 'State_Tangier-Tetouan',
 'State_Tashkent',
 'State_Tashkent Province',
 'State_Telangana',
 'State_UT',
 'State_Uasin Gishu',
 'State_Ulaanbaatar',
 'State_Upper West',
 'State_Uttar Pradesh',
 'State_VA',
 'State_VT',
 'State_Volta',
 'State_WA',
 'State_WEST COAST DIVISION',
 'State_WI',
 'State_WV',
 'State_WY',
 'State_West',
 'State_West Bengal',
 'State_West Coast Division',
 'State_Western',
 'State_Western Area',
 'State_Western Cape',
 'State_Western Highlands',
 'State_Yangon',
 'State_Zurich',
 'Gender_M',
 'Gender_Not Declared',
 'Ethnicity_Eth-2',
 'Ethnicity_Eth-3',
 'Ethnicity_Eth-4',
 'Ethnicity_Eth-5',
 'Ethnicity_Eth-6',
 'Ethnicity_Eth-7',
 'Ethnicity_Eth-8',
 'Ethnicity_Eth-9',
 'Ethnicity_Not Declared',
 'Origin Source_ACT Tape Load',
 'Origin Source_Bison Day Attended',
 'Origin Source_Bison Day Registration',
 'Origin Source_CLT Application',
 'Origin Source_CLT Prospect',
 'Origin Source_CLT Score',
 'Origin Source_Campus Visit Attended',
 'Origin Source_Campus Visit Registration',
 'Origin Source_Capture Higher Ed',
 'Origin Source_Christian Connector',
 'Origin Source_Christian Connector Web Response',
 'Origin Source_Church Visit',
 'Origin Source_Clark Higher Ed Leads',
 'Origin Source_Clark Higher Ed Paid Social',
 'Origin Source_Clark Higher Ed Prospect',
 'Origin Source_Clark Higher Ed Quick App',
 'Origin Source_Clark Higher Ed Search',
 'Origin Source_CollegExpress',
 'Origin Source_College Fair Contact',
 'Origin Source_College Raptor',
 'Origin Source_Empower Conference',
 'Origin Source_Encoura',
 'Origin Source_Encoura Affinity Connection',
 'Origin Source_FAFSA',
 'Origin Source_Falls Creek',
 'Origin Source_GTCF Matchmaker',
 'Origin Source_GenWhy',
 'Origin Source_Graduate Website Inquiry',
 'Origin Source_High School Visit',
 'Origin Source_Inquiry Card',
 'Origin Source_Inquiry Form',
 'Origin Source_Jump Forward Athletic Website',
 'Origin Source_NRCCUA Declared Names',
 'Origin Source_New Mexico Annual Convention',
 'Origin Source_Next Step Magazine',
 'Origin Source_Niche Inquiries',
 'Origin Source_Niche Prospects',
 'Origin Source_Night on the Hill Reservation',
 'Origin Source_Not Declared',
 'Origin Source_Oklahoma Promise',
 'Origin Source_Online Application',
 'Origin Source_Paper Application',
 'Origin Source_Phone Call - Successful',
 'Origin Source_Phone Call - Unsuccessful',
 'Origin Source_Phone Call - Voicemail',
 'Origin Source_Private Colleges & Universities',
 'Origin Source_RNL Junior Search',
 'Origin Source_RNL Sophomore Search',
 'Origin Source_Referral - OBU Faculty Member',
 'Origin Source_SAT Score',
 'Origin Source_STEM Camp',
 'Origin Source_Southern Baptist Convention',
 'Origin Source_StriveScan - Connections',
 'Origin Source_StriveScan - Scans',
 'Origin Source_Super Summer',
 'Origin Source_Text Message',
 'Origin Source_Text Message - Outgoing',
 'Origin Source_Transcript Received',
 'Origin Source_Website Inquiry',
 'Student Type_Readmit',
 'Student Type_Second Degree',
 'Student Type_Test Optional',
 'Student Type_Transfer',
 'Student Type_Transfer (24+ Hours)',
 'Major_Accounting, Interdisciplinary Emphasis',
 'Major_Alternative Teaching Certificate',
 'Major_Applied Mathematics: Actuarial and Financial Math Emphasis',
 'Major_Applied Mathematics: Data Science Emphasis',
 'Major_Art',
 'Major_Art Education, P-12',
 'Major_Biblical and Theological Studies',
 'Major_Biblical and Theological Studies, Biblical Language Emphasis',
 'Major_Biblical and Theological Studies, Biblical Studies Emphasis',
 'Major_Biblical and Theological Studies, History and Theology Emphasis',
 'Major_Biblical and Theological Studies, Practical Theology Emphasis',
 'Major_Biochemistry',
 'Major_Biology',
 'Major_Biology, Forensic Emphasis',
 'Major_Business Administration',
 'Major_Chemistry',
 'Major_Chemistry, Forensic Emphasis',
 'Major_Christian Ministry',
 'Major_Christian Ministry, Pastoral Ministry Emphasis',
 'Major_Christian Ministry, Student and Family Ministry Emphasis',
 "Major_Christian Ministry, Women's Ministry Emphasis",
 'Major_Christian Studies',
 'Major_Communication Studies',
 'Major_Computer Information Systems',
 'Major_Computer Science',
 'Major_Computer Science, Cybersecurity Emphasis',
 'Major_Computer Science, Interdisciplinary Emphasis',
 'Major_Corporate Innovation',
 'Major_Creative Media',
 'Major_Creative Writing',
 'Major_Criminal Justice',
 'Major_Cross-Cultural Ministry',
 'Major_Early Childhood Education',
 'Major_Elementary Education',
 'Major_Engineering - Electrical Engineering',
 'Major_Engineering - Mechanical Engineering',
 'Major_Engineering - Systems Engineering',
 'Major_English',
 'Major_English Education, Secondary',
 'Major_Exercise Science, Human Performance Emphasis',
 'Major_Exercise Science, Pre-Allied Health Emphasis',
 'Major_Family Science',
 'Major_Family Therapy',
 'Major_Finance',
 'Major_Fine Arts',
 'Major_Forensic Psychology',
 'Major_Global Marketplace Engagement, Business Emphasis',
 'Major_Global Marketplace Engagement, Global Education Emphasis',
 'Major_Global Marketplace Engagement, Graphic Design Emphasis',
 'Major_Global Marketplace Engagement, Math Education Emphasis',
 'Major_Global Marketplace Engagement, Political Science Emphasis',
 'Major_Global Marketplace Engagement, Spanish Emphasis',
 'Major_Global Marketplace Engagement, TESOL Emphasis',
 'Major_Graphic Design',
 'Major_History',
 'Major_Interdisciplinary',
 'Major_Interdisciplinary Studies',
 'Major_International Business',
 'Major_Journalism and Mass Communication, Journalism Emphasis',
 'Major_Journalism and Mass Communication, Media Production Emphasis',
 'Major_MBA in Transformational Leadership',
 'Major_Management',
 'Major_Marketing',
 'Major_Master of Arts in Christian Studies: Biblical and Theological Studies (In-Person)',
 'Major_Master of Arts in Christian Studies: Biblical and Theological Studies (Online)',
 'Major_Mathematics',
 'Major_Mathematics Education, Secondary',
 'Major_Middle School Education',
 'Major_Music Composition',
 'Major_Music Education',
 'Major_Music Education, Instrumental Certificate P-12',
 'Major_Musical Arts',
 'Major_Natural Science',
 'Major_Not Declared',
 'Major_Nursing',
 'Major_Philosophy',
 'Major_Philosophy, Apologetics Emphasis',
 'Major_Physics',
 'Major_Piano Performance, Pedagogy Emphasis',
 'Major_Political Science',
 'Major_Project Management',
 'Major_Psychology',
 'Major_Psychology, Pre-Counseling',
 'Major_Science Education, Secondary',
 'Major_Social Sciences Education, Secondary',
 'Major_Sociology',
 'Major_Software Engineering',
 'Major_Spanish Education, P-12',
 'Major_Special Education, Early Childhood Track',
 'Major_Special Education, Elementary Track',
 'Major_Sport Psychology',
 'Major_Sports Communication',
 'Major_Sports and Recreation, Athletic Coaching Emphasis',
 'Major_Sports and Recreation, Camp Administration Emphasis',
 'Major_Sports and Recreation, Sports Ministry Emphasis',
 'Major_Sports and Recreation, Sports and Recreation Management Emphasis',
 'Major_Theatre',
 'Major_Undecided',
 'Major_Vocal Performance',
 'Major_Worship Studies',
 'Athlete_Y',
 "Sport_Basketball (Men's)",
 "Sport_Basketball (Women's)",
 'Sport_Dance',
 'Sport_Football',
 'Sport_Golf',
 'Sport_Marching Band',
 'Sport_Not Declared',
 'Sport_STUNT',
 'Sport_Soccer',
 'Sport_Softball',
 "Sport_Track & Field (Men's)",
 "Sport_Track & Field (Women's)",
 'Sport_Volleyball',
 'Raley College Tag Exists_Y',
 'Recruiting Territory_Graduate',
 'Recruiting Territory_Homeschool',
 'Recruiting Territory_P01',
 'Recruiting Territory_P02',
 'Recruiting Territory_Raley College',
 'Recruiting Territory_T00',
 'Recruiting Territory_T01',
 'Recruiting Territory_T02',
 'Recruiting Territory_T03',
 'Recruiting Territory_T04',
 'Recruiting Territory_T05',
 'Recruiting Territory_T06',
 'Recruiting Territory_T07',
 'Counselor_C10',
 'Counselor_C11',
 'Counselor_C12',
 'Counselor_C13',
 'Counselor_C14',
 'Counselor_C2',
 'Counselor_C3',
 'Counselor_C4',
 'Counselor_C5',
 'Counselor_C6',
 'Counselor_C7',
 'Counselor_C8',
 "Counselor_C9'"
 ]


reference_dict = {'country': ['ARE',
  'ARG',
  'BDI',
  'BEN',
  'BFA',
  'BGD',
  'BHS',
  'BRA',
  'BRB',
  'BWA',
  'CAN',
  'CHE',
  'CHL',
  'CMR',
  'COD',
  'CUB',
  'CYP',
  'CZE',
  'DEU',
  'ESP',
  'ETH',
  'FRA',
  'GBR',
  'GHA',
  'GMB',
  'HKG',
  'HND',
  'IND',
  'IRN',
  'ITA',
  'JAM',
  'KAZ',
  'KEN',
  'KWT',
  'LBR',
  'LKA',
  'LSO',
  'MAR',
  'MDG',
  'MEX',
  'MMR',
  'MNG',
  'MWI',
  'NAM',
  'NGA',
  'NLD',
  'NPL',
  'NZL',
  'Not Declared',
  'OMN',
  'PAK',
  'PER',
  'PHL',
  'PNG',
  'PSE',
  'ROU',
  'RWA',
  'SAU',
  'SEN',
  'SLE',
  'SLV',
  'SSD',
  'SWZ',
  'TGO',
  'TJK',
  'TUR',
  'TZA',
  'UGA',
  'URY',
  'USA',
  'UZB',
  'VEN',
  'VNM',
  'WSM',
  'ZAF',
  'ZMB',
  'ZWE'],
 'state': ['AB',
  'AE',
  'AK',
  'AL',
  'AP',
  'AR',
  'AZ',
  'BC',
  'CA',
  'CO',
  'CT',
  'DC',
  'DE',
  'FL',
  'GA',
  'HI',
  'IA',
  'ID',
  'IL',
  'IN',
  'KS',
  'KY',
  'LA',
  'MA',
  'MD',
  'ME',
  'MI',
  'MN',
  'MO',
  'MS',
  'MT',
  'NC',
  'ND',
  'NE',
  'NH',
  'NJ',
  'NM',
  'NV',
  'NY',
  'OH',
  'OK',
  'ON',
  'OR',
  'PA',
  'PR',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VA',
  'VT',
  'WA',
  'WI',
  'WV',
  'WY',
  '-- Select --',
  'ADDIS ABABA',
  'ANAMBRA',
  'ASHANTI',
  'ASHANTI REGION',
  'Abia',
  'Addis Ababa',
  'Akwa Ibom',
  'Al Farwaniyah',
  'Almaty',
  'Anambra',
  'Andhra Pradesh',
  'Antananarivo',
  'Araucania',
  'Artigas',
  'Ashanti',
  'BONO EAST',
  'Bagmati',
  'Balochistan',
  'Banjul',
  'Baringo',
  'Barisal',
  'Bihar',
  'Bolivar',
  'Bong',
  'Brong-Ahafo',
  'Buenos Aires',
  'Bujumbura',
  'CAPITAL CITY',
  'CENTRAL REGION',
  'Central',
  'Central Equatoria',
  'Central River Division',
  'Centre',
  'Chittagong Division',
  'Colon',
  'Cross River',
  'DAKAR',
  'Dar es Salaam',
  'Delhi',
  'Delta',
  'Dhaka Division',
  'Doukkala-Abda',
  'Dubai',
  'Dushanbe',
  'ENUGU STATE',
  'ETHIOPIA',
  'East Kazakhstan',
  'Eastern',
  'Eastern Cape',
  'Eastern Visayas',
  'Edo',
  'Elgeyo-Marakwet',
  'Enga',
  'Enugu',
  "FARG'ONA VILOYATI",
  'FERGANA',
  'Famagusta',
  'Fars',
  'Federal Capital Territory',
  'Fergana',
  'Francisco Morazan',
  'GHANA',
  'GREATER ACCRA',
  'GUATENG',
  'Gandaki',
  'Garissa',
  'Gauteng',
  'Gaza',
  'Gilgit-Baltistan',
  'Grand Casablanca',
  'Greater Accra',
  'Harare',
  'Harghita',
  'Herat',
  'Hesse',
  'Hhohho',
  'ISLAMABAD CAPITAL TERRITORY',
  'Imo',
  'Istanbul',
  'JANAKPUR',
  'KANESHIE',
  'KERICHO',
  'Kaduna',
  'Kericho',
  'Khyber Pakhtunkhwa',
  'Kiambu',
  'Kigali',
  'Kinshasa',
  'Kisii',
  'KwaZulu-Natal',
  'Kwara',
  'LAGOS',
  'Lagos',
  'Lambayeque',
  'Limpopo',
  'Littoral',
  'Madhesh Pradesh',
  'Madhya Pashchimanchal',
  'Madrid Autonomous Community',
  'Maharashtra',
  'Manicaland',
  'Manipur',
  'Manzini',
  'Maritime',
  'Maseru',
  'Metro Manila',
  'Mexico City',
  'Minas Gerais',
  'Mombasa',
  'Montserrado',
  'Morazan',
  'Mpumalanga',
  'Muscat',
  'Nairobi County',
  'Namangan',
  'Nandi',
  'New Providence',
  'Nimba',
  'North Kivu',
  'North Rhine-Westphalia',
  'Northern',
  'Northern Ireland',
  'Northwest',
  'Not Declared',
  'Odisha',
  'Ogun',
  'Ondo',
  'Oromia',
  'Oshana',
  'Osun',
  'Oyo',
  'Oyo State',
  'PUNJAB',
  'Parana',
  'Piedmont',
  'Plateau',
  'Prague',
  'Punjab',
  'Purwanchal',
  'Qashqadaryo',
  'Quang Nam',
  'RIO GRANDE DO NORTE',
  'Rivers',
  'SANCTI SPIRITUS',
  'SOUTHWEST REGION',
  'Sabaragamuwa',
  'Sagaing',
  'Saint Catherine',
  'Saint James',
  'Saint Philip',
  'Samarqand',
  'Sao Paulo',
  'Scotland',
  'Sindh',
  'Southern',
  'Southwest',
  'Sudur Pashchimanchal',
  'Sylhet Division',
  'Tangier-Tetouan',
  'Tashkent',
  'Tashkent Province',
  'Telangana',
  'Uasin Gishu',
  'Ulaanbaatar',
  'Upper West',
  'Uttar Pradesh',
  'Volta',
  'WEST COAST DIVISION',
  'West',
  'West Bengal',
  'West Coast Division',
  'Western',
  'Western Area',
  'Western Cape',
  'Western Highlands',
  'Yangon',
  'Zurich'],
 'gender': ['M', 'Not Declared'],
 'ethnicity': ['Eth-1',
  'Eth-2',
  'Eth-3',
  'Eth-4',
  'Eth-5',
  'Eth-6',
  'Eth-7',
  'Eth-8',
  'Eth-9',
  'Not Declared'],
 'originSource': ['ACT Tape Load',
  'Bison Day Attended',
  'Bison Day Registration',
  'CLT Application',
  'CLT Prospect',
  'CLT Score',
  'Campus Visit Attended',
  'Campus Visit Registration',
  'Capture Higher Ed',
  'Christian Connector',
  'Christian Connector Web Response',
  'Church Visit',
  'Clark Higher Ed Leads',
  'Clark Higher Ed Paid Social',
  'Clark Higher Ed Prospect',
  'Clark Higher Ed Quick App',
  'Clark Higher Ed Search',
  'CollegExpress',
  'College Fair Contact',
  'College Raptor',
  'Empower Conference',
  'Encoura',
  'Encoura Affinity Connection',
  'FAFSA',
  'Falls Creek',
  'GTCF Matchmaker',
  'GenWhy',
  'Graduate Website Inquiry',
  'High School Visit',
  'Inquiry Card',
  'Inquiry Form',
  'Jump Forward Athletic Website',
  'NRCCUA Declared Names',
  'New Mexico Annual Convention',
  'Next Step Magazine',
  'Niche Inquiries',
  'Niche Prospects',
  'Night on the Hill Reservation',
  'Not Declared',
  'Oklahoma Promise',
  'Online Application',
  'Paper Application',
  'Phone Call - Successful',
  'Phone Call - Unsuccessful',
  'Phone Call - Voicemail',
  'Private Colleges & Universities',
  'RNL Junior Search',
  'RNL Sophomore Search',
  'Referral - OBU Faculty Member',
  'SAT Score',
  'STEM Camp',
  'Southern Baptist Convention',
  'StriveScan - Connections',
  'StriveScan - Scans',
  'Super Summer',
  'Text Message',
  'Text Message - Outgoing',
  'Transcript Received',
  'Website Inquiry'],
 'studentType': ['First-Time Freshman',
  'Readmit',
  'Second Degree',
  'Test Optional',
  'Transfer',
  'Transfer (24+ Hours)'],
 'major': ['Accounting, Interdisciplinary Emphasis',
  'Alternative Teaching Certificate',
  'Applied Mathematics: Actuarial and Financial Math Emphasis',
  'Applied Mathematics: Data Science Emphasis',
  'Art',
  'Art Education, P-12',
  'Biblical and Theological Studies',
  'Biblical and Theological Studies, Biblical Language Emphasis',
  'Biblical and Theological Studies, Biblical Studies Emphasis',
  'Biblical and Theological Studies, History and Theology Emphasis',
  'Biblical and Theological Studies, Practical Theology Emphasis',
  'Biochemistry',
  'Biology',
  'Biology, Forensic Emphasis',
  'Business Administration',
  'Chemistry',
  'Chemistry, Forensic Emphasis',
  'Christian Ministry',
  'Christian Ministry, Pastoral Ministry Emphasis',
  'Christian Ministry, Student and Family Ministry Emphasis',
  "Christian Ministry, Women's Ministry Emphasis",
  'Christian Studies',
  'Communication Studies',
  'Computer Information Systems',
  'Computer Science',
  'Computer Science, Cybersecurity Emphasis',
  'Computer Science, Interdisciplinary Emphasis',
  'Corporate Innovation',
  'Creative Media',
  'Creative Writing',
  'Criminal Justice',
  'Cross-Cultural Ministry',
  'Early Childhood Education',
  'Elementary Education',
  'Engineering - Electrical Engineering',
  'Engineering - Mechanical Engineering',
  'Engineering - Systems Engineering',
  'English',
  'English Education, Secondary',
  'Exercise Science, Human Performance Emphasis',
  'Exercise Science, Pre-Allied Health Emphasis',
  'Family Science',
  'Family Therapy',
  'Finance',
  'Fine Arts',
  'Forensic Psychology',
  'Global Marketplace Engagement, Business Emphasis',
  'Global Marketplace Engagement, Global Education Emphasis',
  'Global Marketplace Engagement, Graphic Design Emphasis',
  'Global Marketplace Engagement, Math Education Emphasis',
  'Global Marketplace Engagement, Political Science Emphasis',
  'Global Marketplace Engagement, Spanish Emphasis',
  'Global Marketplace Engagement, TESOL Emphasis',
  'Graphic Design',
  'History',
  'Interdisciplinary',
  'Interdisciplinary Studies',
  'International Business',
  'Journalism and Mass Communication, Journalism Emphasis',
  'Journalism and Mass Communication, Media Production Emphasis',
  'MBA in Transformational Leadership',
  'Management',
  'Marketing',
  'Master of Arts in Christian Studies: Biblical and Theological Studies (In-Person)',
  'Master of Arts in Christian Studies: Biblical and Theological Studies (Online)',
  'Mathematics',
  'Mathematics Education, Secondary',
  'Middle School Education',
  'Music Composition',
  'Music Education',
  'Music Education, Instrumental Certificate P-12',
  'Musical Arts',
  'Natural Science',
  'Not Declared',
  'Nursing',
  'Philosophy',
  'Philosophy, Apologetics Emphasis',
  'Physics',
  'Piano Performance, Pedagogy Emphasis',
  'Political Science',
  'Project Management',
  'Psychology',
  'Psychology, Pre-Counseling',
  'Science Education, Secondary',
  'Social Sciences Education, Secondary',
  'Sociology',
  'Software Engineering',
  'Spanish Education, P-12',
  'Special Education, Early Childhood Track',
  'Special Education, Elementary Track',
  'Sport Psychology',
  'Sports Communication',
  'Sports and Recreation, Athletic Coaching Emphasis',
  'Sports and Recreation, Camp Administration Emphasis',
  'Sports and Recreation, Sports Ministry Emphasis',
  'Sports and Recreation, Sports and Recreation Management Emphasis',
  'Theatre',
  'Undecided',
  'Vocal Performance',
  'Worship Studies'],
 'athlete': ['Y', 'Not Declared'],
 'sport': ["Basketball (Men's)",
  "Basketball (Women's)",
  'Dance',
  'Football',
  'Golf',
  'Marching Band',
  'Not Declared',
  'STUNT',
  'Soccer',
  'Softball',
  "Track & Field (Men's)",
  "Track & Field (Women's)",
  'Volleyball'],
 'raleyCollegeTagExists': ['Y', 'Not Declared'],
 'recruitingTerritory': ['Graduate',
  'Homeschool',
  'P01',
  'P02',
  'Raley College',
  'T00',
  'T01',
  'T02',
  'T03',
  'T04',
  'T05',
  'T06',
  'T07'],
 'counselor': ['C10',
  'C11',
  'C12',
  'C13',
  'C14',
  'C2',
  'C3',
  'C4',
  'C5',
  'C6',
  'C7',
  'C8',
  "C9'"]}